export const taskSchema = {
  entity: 'tasks',
  fields: {
    id: 'string',
    title: 'string',
    description: 'string',
    status: 'string',
    section: 'string',
    category: 'string',
    priority: 'string',
    energy: 'string',
    linkedGoalIds: 'array',
    linkedSubjectIds: 'array',
    linkedScheduleIds: 'array',
    linkedJournalIds: 'array',
    linkedFinanceIds: 'array',
    linkedContactIds: 'array',
    deadline: 'date',
    estimatedTime: 'string',
    tags: 'array',
    progress: 'number',
    archivedAt: 'date',
    completedAt: 'date',
    createdAt: 'date',
    updatedAt: 'date',
  },
  defaults: {
    title: 'Untitled Task',
    description: '',
    status: 'planned',
    section: 'Planned',
    category: 'System',
    priority: 'medium',
    energy: 'medium',
    progress: 0,
    tags: [],
    linkedGoalIds: [],
    linkedSubjectIds: [],
    linkedScheduleIds: [],
    linkedJournalIds: [],
    linkedFinanceIds: [],
    linkedContactIds: [],
    deadline: null,
    estimatedTime: '30m',
    archivedAt: null,
    completedAt: null,
  },
};
