export const taskSchema = {
  entity: "tasks",
  fields: {
    id: "string",
    title: "string",
    description: "string",
    status: "string",
    section: "string",
    category: "string",
    priority: "string",
    energy: "string",
    linkedGoalIds: "array",
    linkedSubjectIds: "array",
    linkedScheduleIds: "array",
    linkedJournalIds: "array",
    linkedFinanceIds: "array",
    linkedContactIds: "array",
    deadline: "date",
    estimatedTime: "string",
    tags: "array",
    progress: "number",
    scheduleId: "string",
    createdAt: "date",
    updatedAt: "date"
  },
  defaults: {
    title: "Untitled Task",
    status: "todo",
    priority: "Medium",
    energy: "medium",
    progress: 0,
    tags: [],
    linkedGoalIds: [],
    linkedSubjectIds: [],
    linkedScheduleIds: [],
    linkedJournalIds: [],
    linkedFinanceIds: [],
    linkedContactIds: []
  }
};
