export const taskSchema = {
  entity: 'tasks',
  fields: {
    id: 'string',
    title: 'string',
    description: 'string',
    bucket: 'string',
    originalBucket: 'string',
    category: 'string',
    priority: 'string',
    subTags: 'array',
    linkedGoalIds: 'array',
    linkedAcademicIds: 'array',
    linkedScheduleIds: 'array',
    linkedJournalIds: 'array',
    dueDate: 'date',
    progress: 'number',
    completed: 'boolean',
    completedAt: 'date',
    completionNotes: 'string',
    archived: 'boolean',
    createdAt: 'date',
    updatedAt: 'date',
  },
  defaults: {
    title: 'Untitled Task',
    description: '',
    bucket: 'undefined',
    originalBucket: 'undefined',
    category: 'System',
    priority: 'medium',
    subTags: [],
    progress: 0,
    linkedGoalIds: [],
    linkedAcademicIds: [],
    linkedScheduleIds: [],
    linkedJournalIds: [],
    dueDate: null,
    completed: false,
    completedAt: null,
    completionNotes: '',
    archived: false,
  },
};
